#!/bin/bash

source /Users/samatkins/code/util-scripts/env/bin/activate;

python /Users/samatkins/code/util-scripts/src/set_creds.py $1;

source /Users/samatkins/.bh_creds/aws;

echo "Credentials set.";
